// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: pkg/graph/graph.proto

package graph

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_GetVertex_FullMethodName    = "/graph.Service/GetVertex"
	Service_CreateVertex_FullMethodName = "/graph.Service/CreateVertex"
	Service_UpdateVertex_FullMethodName = "/graph.Service/UpdateVertex"
	Service_DeleteVertex_FullMethodName = "/graph.Service/DeleteVertex"
	Service_GetEdge_FullMethodName      = "/graph.Service/GetEdge"
	Service_CreateEdge_FullMethodName   = "/graph.Service/CreateEdge"
	Service_UpdateEdge_FullMethodName   = "/graph.Service/UpdateEdge"
	Service_DeleteEdge_FullMethodName   = "/graph.Service/DeleteEdge"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service represents the graph operations.
type ServiceClient interface {
	GetVertex(ctx context.Context, in *GetVertexRequest, opts ...grpc.CallOption) (*Vertex, error)
	CreateVertex(ctx context.Context, in *Vertex, opts ...grpc.CallOption) (*Status, error)
	UpdateVertex(ctx context.Context, in *Vertex, opts ...grpc.CallOption) (*Status, error)
	DeleteVertex(ctx context.Context, in *VertexId, opts ...grpc.CallOption) (*Status, error)
	GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*Edge, error)
	CreateEdge(ctx context.Context, in *Edge, opts ...grpc.CallOption) (*Status, error)
	UpdateEdge(ctx context.Context, in *Edge, opts ...grpc.CallOption) (*Status, error)
	DeleteEdge(ctx context.Context, in *EdgeId, opts ...grpc.CallOption) (*Status, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetVertex(ctx context.Context, in *GetVertexRequest, opts ...grpc.CallOption) (*Vertex, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vertex)
	err := c.cc.Invoke(ctx, Service_GetVertex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreateVertex(ctx context.Context, in *Vertex, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Service_CreateVertex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpdateVertex(ctx context.Context, in *Vertex, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Service_UpdateVertex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DeleteVertex(ctx context.Context, in *VertexId, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Service_DeleteVertex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...grpc.CallOption) (*Edge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Edge)
	err := c.cc.Invoke(ctx, Service_GetEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreateEdge(ctx context.Context, in *Edge, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Service_CreateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpdateEdge(ctx context.Context, in *Edge, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Service_UpdateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DeleteEdge(ctx context.Context, in *EdgeId, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Service_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
//
// Service represents the graph operations.
type ServiceServer interface {
	GetVertex(context.Context, *GetVertexRequest) (*Vertex, error)
	CreateVertex(context.Context, *Vertex) (*Status, error)
	UpdateVertex(context.Context, *Vertex) (*Status, error)
	DeleteVertex(context.Context, *VertexId) (*Status, error)
	GetEdge(context.Context, *GetEdgeRequest) (*Edge, error)
	CreateEdge(context.Context, *Edge) (*Status, error)
	UpdateEdge(context.Context, *Edge) (*Status, error)
	DeleteEdge(context.Context, *EdgeId) (*Status, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) GetVertex(context.Context, *GetVertexRequest) (*Vertex, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVertex not implemented")
}
func (UnimplementedServiceServer) CreateVertex(context.Context, *Vertex) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVertex not implemented")
}
func (UnimplementedServiceServer) UpdateVertex(context.Context, *Vertex) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVertex not implemented")
}
func (UnimplementedServiceServer) DeleteVertex(context.Context, *VertexId) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVertex not implemented")
}
func (UnimplementedServiceServer) GetEdge(context.Context, *GetEdgeRequest) (*Edge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEdge not implemented")
}
func (UnimplementedServiceServer) CreateEdge(context.Context, *Edge) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEdge not implemented")
}
func (UnimplementedServiceServer) UpdateEdge(context.Context, *Edge) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEdge not implemented")
}
func (UnimplementedServiceServer) DeleteEdge(context.Context, *EdgeId) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call pancis, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_GetVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVertexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetVertex(ctx, req.(*GetVertexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreateVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vertex)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateVertex(ctx, req.(*Vertex))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UpdateVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vertex)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UpdateVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UpdateVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UpdateVertex(ctx, req.(*Vertex))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DeleteVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VertexId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DeleteVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_DeleteVertex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DeleteVertex(ctx, req.(*VertexId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetEdge(ctx, req.(*GetEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Edge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateEdge(ctx, req.(*Edge))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UpdateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Edge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UpdateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UpdateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UpdateEdge(ctx, req.(*Edge))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EdgeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DeleteEdge(ctx, req.(*EdgeId))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graph.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVertex",
			Handler:    _Service_GetVertex_Handler,
		},
		{
			MethodName: "CreateVertex",
			Handler:    _Service_CreateVertex_Handler,
		},
		{
			MethodName: "UpdateVertex",
			Handler:    _Service_UpdateVertex_Handler,
		},
		{
			MethodName: "DeleteVertex",
			Handler:    _Service_DeleteVertex_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _Service_GetEdge_Handler,
		},
		{
			MethodName: "CreateEdge",
			Handler:    _Service_CreateEdge_Handler,
		},
		{
			MethodName: "UpdateEdge",
			Handler:    _Service_UpdateEdge_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _Service_DeleteEdge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/graph/graph.proto",
}
