// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.4
// source: internal/control/server/storage/storage.proto

package storage

import (
	control "github.com/bcrusu/scout/internal/control"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// [optional] The FSM checks its current version with the one
	// provided here and rejects the write if they do not match. Will
	// be used for scenarios where changes in state between read and
	// write are not allowed. For example, the partition assignment
	// component will read the current server list from the FSM, perform
	// the partition placement logic, and then write the changes back
	// to the FSM. Any modifications in the server list between the read
	// and write can result in unexpected state where missing servers are
	// assigned paritions. For this kind of scenarios it is preferable
	// to reject the write and have the component retry by reading
	// latest state, restarting the process from beginning.
	IfMatch uint64 `protobuf:"varint,1,opt,name=if_match,json=ifMatch,proto3" json:"if_match,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Command_Bootstrap
	//	*Command_Register
	//	*Command_UpdateStatus
	//	*Command_InitAssignments
	//	*Command_UpdateAssignments
	Payload isCommand_Payload `protobuf_oneof:"payload"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetIfMatch() uint64 {
	if x != nil {
		return x.IfMatch
	}
	return 0
}

func (m *Command) GetPayload() isCommand_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Command) GetBootstrap() *Bootstrap {
	if x, ok := x.GetPayload().(*Command_Bootstrap); ok {
		return x.Bootstrap
	}
	return nil
}

func (x *Command) GetRegister() *Register {
	if x, ok := x.GetPayload().(*Command_Register); ok {
		return x.Register
	}
	return nil
}

func (x *Command) GetUpdateStatus() *UpdateStatus {
	if x, ok := x.GetPayload().(*Command_UpdateStatus); ok {
		return x.UpdateStatus
	}
	return nil
}

func (x *Command) GetInitAssignments() *InitAssignments {
	if x, ok := x.GetPayload().(*Command_InitAssignments); ok {
		return x.InitAssignments
	}
	return nil
}

func (x *Command) GetUpdateAssignments() *UpdateAssignments {
	if x, ok := x.GetPayload().(*Command_UpdateAssignments); ok {
		return x.UpdateAssignments
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_Bootstrap struct {
	Bootstrap *Bootstrap `protobuf:"bytes,2,opt,name=bootstrap,proto3,oneof"`
}

type Command_Register struct {
	Register *Register `protobuf:"bytes,3,opt,name=register,proto3,oneof"`
}

type Command_UpdateStatus struct {
	UpdateStatus *UpdateStatus `protobuf:"bytes,4,opt,name=update_status,json=updateStatus,proto3,oneof"`
}

type Command_InitAssignments struct {
	InitAssignments *InitAssignments `protobuf:"bytes,5,opt,name=init_assignments,json=initAssignments,proto3,oneof"`
}

type Command_UpdateAssignments struct {
	UpdateAssignments *UpdateAssignments `protobuf:"bytes,6,opt,name=update_assignments,json=updateAssignments,proto3,oneof"`
}

func (*Command_Bootstrap) isCommand_Payload() {}

func (*Command_Register) isCommand_Payload() {}

func (*Command_UpdateStatus) isCommand_Payload() {}

func (*Command_InitAssignments) isCommand_Payload() {}

func (*Command_UpdateAssignments) isCommand_Payload() {}

type Bootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterName string              `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Servers     []*Bootstrap_Server `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	// The number of partitions in the data storage cluster. It is set
	// during cluster bootstrap and will not be changed later. This way,
	// it implicitly sets an upper limit on the total data storage capacity
	// achievable in the cluster.
	// Each partition maps one-to-one to a multiraft replication group.
	PartitionCount uint32 `protobuf:"varint,3,opt,name=partition_count,json=partitionCount,proto3" json:"partition_count,omitempty"`
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Bootstrap) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Bootstrap) GetServers() []*Bootstrap_Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetPartitionCount() uint32 {
	if x != nil {
		return x.PartitionCount
	}
	return 0
}

type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type control.ServerType `protobuf:"varint,1,opt,name=type,proto3,enum=control.ServerType" json:"type,omitempty"`
	// Unique token.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// The addres where the server will be contacted.
	Address string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Tags    []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetType() control.ServerType {
	if x != nil {
		return x.Type
	}
	return control.ServerType(0)
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Register) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Register) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers    map[uint64]*UpdateStatus_Server    `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Partitions map[uint32]*UpdateStatus_Partition `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStatus) GetServers() map[uint64]*UpdateStatus_Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *UpdateStatus) GetPartitions() map[uint32]*UpdateStatus_Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type InitAssignments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add []*InitAssignments_Add `protobuf:"bytes,1,rep,name=add,proto3" json:"add,omitempty"`
}

func (x *InitAssignments) Reset() {
	*x = InitAssignments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitAssignments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAssignments) ProtoMessage() {}

func (x *InitAssignments) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAssignments.ProtoReflect.Descriptor instead.
func (*InitAssignments) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *InitAssignments) GetAdd() []*InitAssignments_Add {
	if x != nil {
		return x.Add
	}
	return nil
}

type UpdateAssignments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IfMatch uint64                      `protobuf:"varint,1,opt,name=if_match,json=ifMatch,proto3" json:"if_match,omitempty"`
	Add     []*UpdateAssignments_Add    `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	Update  []*UpdateAssignments_Update `protobuf:"bytes,3,rep,name=update,proto3" json:"update,omitempty"`
	Remove  []*UpdateAssignments_Remove `protobuf:"bytes,4,rep,name=remove,proto3" json:"remove,omitempty"`
}

func (x *UpdateAssignments) Reset() {
	*x = UpdateAssignments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAssignments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssignments) ProtoMessage() {}

func (x *UpdateAssignments) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssignments.ProtoReflect.Descriptor instead.
func (*UpdateAssignments) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAssignments) GetIfMatch() uint64 {
	if x != nil {
		return x.IfMatch
	}
	return 0
}

func (x *UpdateAssignments) GetAdd() []*UpdateAssignments_Add {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateAssignments) GetUpdate() []*UpdateAssignments_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateAssignments) GetRemove() []*UpdateAssignments_Remove {
	if x != nil {
		return x.Remove
	}
	return nil
}

type Bootstrap_Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Bootstrap_Server) Reset() {
	*x = Bootstrap_Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bootstrap_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap_Server) ProtoMessage() {}

func (x *Bootstrap_Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap_Server.ProtoReflect.Descriptor instead.
func (*Bootstrap_Server) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Bootstrap_Server) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bootstrap_Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bootstrap_Server) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateStatus_Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastSeen    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	LastAddress string                 `protobuf:"bytes,2,opt,name=last_address,json=lastAddress,proto3" json:"last_address,omitempty"`
}

func (x *UpdateStatus_Server) Reset() {
	*x = UpdateStatus_Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatus_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus_Server) ProtoMessage() {}

func (x *UpdateStatus_Server) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus_Server.ProtoReflect.Descriptor instead.
func (*UpdateStatus_Server) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpdateStatus_Server) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *UpdateStatus_Server) GetLastAddress() string {
	if x != nil {
		return x.LastAddress
	}
	return ""
}

type UpdateStatus_Replica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastUpdate   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	AppliedIndex uint64                 `protobuf:"varint,2,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	Ready        bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *UpdateStatus_Replica) Reset() {
	*x = UpdateStatus_Replica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatus_Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus_Replica) ProtoMessage() {}

func (x *UpdateStatus_Replica) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus_Replica.ProtoReflect.Descriptor instead.
func (*UpdateStatus_Replica) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{3, 1}
}

func (x *UpdateStatus_Replica) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *UpdateStatus_Replica) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *UpdateStatus_Replica) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type UpdateStatus_Partition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Replicas      map[string]*UpdateStatus_Replica `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Leader        string                           `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	LeaderTerm    uint64                           `protobuf:"varint,3,opt,name=leader_term,json=leaderTerm,proto3" json:"leader_term,omitempty"`
	CommitedIndex uint64                           `protobuf:"varint,4,opt,name=commited_index,json=commitedIndex,proto3" json:"commited_index,omitempty"`
}

func (x *UpdateStatus_Partition) Reset() {
	*x = UpdateStatus_Partition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStatus_Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus_Partition) ProtoMessage() {}

func (x *UpdateStatus_Partition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus_Partition.ProtoReflect.Descriptor instead.
func (*UpdateStatus_Partition) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{3, 2}
}

func (x *UpdateStatus_Partition) GetReplicas() map[string]*UpdateStatus_Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *UpdateStatus_Partition) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *UpdateStatus_Partition) GetLeaderTerm() uint64 {
	if x != nil {
		return x.LeaderTerm
	}
	return 0
}

func (x *UpdateStatus_Partition) GetCommitedIndex() uint64 {
	if x != nil {
		return x.CommitedIndex
	}
	return 0
}

type InitAssignments_Add struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionId uint32 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	ServerId    uint64 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Voter       bool   `protobuf:"varint,3,opt,name=voter,proto3" json:"voter,omitempty"`
}

func (x *InitAssignments_Add) Reset() {
	*x = InitAssignments_Add{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitAssignments_Add) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAssignments_Add) ProtoMessage() {}

func (x *InitAssignments_Add) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAssignments_Add.ProtoReflect.Descriptor instead.
func (*InitAssignments_Add) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{4, 0}
}

func (x *InitAssignments_Add) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *InitAssignments_Add) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *InitAssignments_Add) GetVoter() bool {
	if x != nil {
		return x.Voter
	}
	return false
}

type UpdateAssignments_Add struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionId uint32 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	ServerId    uint64 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *UpdateAssignments_Add) Reset() {
	*x = UpdateAssignments_Add{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAssignments_Add) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssignments_Add) ProtoMessage() {}

func (x *UpdateAssignments_Add) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssignments_Add.ProtoReflect.Descriptor instead.
func (*UpdateAssignments_Add) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpdateAssignments_Add) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *UpdateAssignments_Add) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type UpdateAssignments_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionId uint32               `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Replica     string               `protobuf:"bytes,2,opt,name=replica,proto3" json:"replica,omitempty"`
	State       control.ReplicaState `protobuf:"varint,3,opt,name=state,proto3,enum=control.ReplicaState" json:"state,omitempty"`
}

func (x *UpdateAssignments_Update) Reset() {
	*x = UpdateAssignments_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAssignments_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssignments_Update) ProtoMessage() {}

func (x *UpdateAssignments_Update) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssignments_Update.ProtoReflect.Descriptor instead.
func (*UpdateAssignments_Update) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{5, 1}
}

func (x *UpdateAssignments_Update) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *UpdateAssignments_Update) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

func (x *UpdateAssignments_Update) GetState() control.ReplicaState {
	if x != nil {
		return x.State
	}
	return control.ReplicaState(0)
}

type UpdateAssignments_Remove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionId uint32 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Replica     string `protobuf:"bytes,2,opt,name=replica,proto3" json:"replica,omitempty"`
}

func (x *UpdateAssignments_Remove) Reset() {
	*x = UpdateAssignments_Remove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_control_server_storage_storage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAssignments_Remove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssignments_Remove) ProtoMessage() {}

func (x *UpdateAssignments_Remove) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_server_storage_storage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssignments_Remove.ProtoReflect.Descriptor instead.
func (*UpdateAssignments_Remove) Descriptor() ([]byte, []int) {
	return file_internal_control_server_storage_storage_proto_rawDescGZIP(), []int{5, 2}
}

func (x *UpdateAssignments_Remove) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *UpdateAssignments_Remove) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

var File_internal_control_server_storage_storage_proto protoreflect.FileDescriptor

var file_internal_control_server_storage_storage_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x1a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8e, 0x03, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x69, 0x66, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x69, 0x66, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x3a, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6f,
	0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73,
	0x74, 0x72, 0x61, 0x70, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x44, 0x0a,
	0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x4d, 0x0a, 0x10, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x61, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x49, 0x6e, 0x69, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x48,
	0x00, 0x52, 0x0f, 0x69, 0x6e, 0x69, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x53, 0x0a, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x48, 0x00, 0x52, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69,
	0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0xdc, 0x01, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x46, 0x0a, 0x06, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x77, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x27, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0xfc, 0x06, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x44, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x73, 0x12, 0x4d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x64, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x09, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53,
	0x65, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x81, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x12, 0x3b, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x1a, 0xa2, 0x02, 0x0a, 0x09, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x65,
	0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x54, 0x65, 0x72, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x65, 0x64,
	0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x62, 0x0a, 0x0d, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3b,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x60, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x3a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x1a, 0x66, 0x0a, 0x0f, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa6, 0x01, 0x0a, 0x0f, 0x49, 0x6e,
	0x69, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x36, 0x0a,
	0x03, 0x61, 0x64, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x52, 0x03, 0x61, 0x64, 0x64, 0x1a, 0x5b, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x6f, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x6f, 0x74,
	0x65, 0x72, 0x22, 0xf0, 0x03, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x66, 0x5f, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x69, 0x66, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x38, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x41, 0x0a,
	0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x41, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x06, 0x72, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x1a, 0x45, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x72, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x45,
	0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x63, 0x72, 0x75, 0x73, 0x75, 0x2f, 0x73, 0x63, 0x6f, 0x75, 0x74,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_control_server_storage_storage_proto_rawDescOnce sync.Once
	file_internal_control_server_storage_storage_proto_rawDescData = file_internal_control_server_storage_storage_proto_rawDesc
)

func file_internal_control_server_storage_storage_proto_rawDescGZIP() []byte {
	file_internal_control_server_storage_storage_proto_rawDescOnce.Do(func() {
		file_internal_control_server_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_control_server_storage_storage_proto_rawDescData)
	})
	return file_internal_control_server_storage_storage_proto_rawDescData
}

var file_internal_control_server_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_control_server_storage_storage_proto_goTypes = []any{
	(*Command)(nil),                  // 0: control.storage.Command
	(*Bootstrap)(nil),                // 1: control.storage.Bootstrap
	(*Register)(nil),                 // 2: control.storage.Register
	(*UpdateStatus)(nil),             // 3: control.storage.UpdateStatus
	(*InitAssignments)(nil),          // 4: control.storage.InitAssignments
	(*UpdateAssignments)(nil),        // 5: control.storage.UpdateAssignments
	(*Bootstrap_Server)(nil),         // 6: control.storage.Bootstrap.Server
	(*UpdateStatus_Server)(nil),      // 7: control.storage.UpdateStatus.Server
	(*UpdateStatus_Replica)(nil),     // 8: control.storage.UpdateStatus.Replica
	(*UpdateStatus_Partition)(nil),   // 9: control.storage.UpdateStatus.Partition
	nil,                              // 10: control.storage.UpdateStatus.ServersEntry
	nil,                              // 11: control.storage.UpdateStatus.PartitionsEntry
	nil,                              // 12: control.storage.UpdateStatus.Partition.ReplicasEntry
	(*InitAssignments_Add)(nil),      // 13: control.storage.InitAssignments.Add
	(*UpdateAssignments_Add)(nil),    // 14: control.storage.UpdateAssignments.Add
	(*UpdateAssignments_Update)(nil), // 15: control.storage.UpdateAssignments.Update
	(*UpdateAssignments_Remove)(nil), // 16: control.storage.UpdateAssignments.Remove
	(control.ServerType)(0),          // 17: control.ServerType
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
	(control.ReplicaState)(0),        // 19: control.ReplicaState
}
var file_internal_control_server_storage_storage_proto_depIdxs = []int32{
	1,  // 0: control.storage.Command.bootstrap:type_name -> control.storage.Bootstrap
	2,  // 1: control.storage.Command.register:type_name -> control.storage.Register
	3,  // 2: control.storage.Command.update_status:type_name -> control.storage.UpdateStatus
	4,  // 3: control.storage.Command.init_assignments:type_name -> control.storage.InitAssignments
	5,  // 4: control.storage.Command.update_assignments:type_name -> control.storage.UpdateAssignments
	6,  // 5: control.storage.Bootstrap.servers:type_name -> control.storage.Bootstrap.Server
	17, // 6: control.storage.Register.type:type_name -> control.ServerType
	10, // 7: control.storage.UpdateStatus.servers:type_name -> control.storage.UpdateStatus.ServersEntry
	11, // 8: control.storage.UpdateStatus.partitions:type_name -> control.storage.UpdateStatus.PartitionsEntry
	13, // 9: control.storage.InitAssignments.add:type_name -> control.storage.InitAssignments.Add
	14, // 10: control.storage.UpdateAssignments.add:type_name -> control.storage.UpdateAssignments.Add
	15, // 11: control.storage.UpdateAssignments.update:type_name -> control.storage.UpdateAssignments.Update
	16, // 12: control.storage.UpdateAssignments.remove:type_name -> control.storage.UpdateAssignments.Remove
	18, // 13: control.storage.UpdateStatus.Server.last_seen:type_name -> google.protobuf.Timestamp
	18, // 14: control.storage.UpdateStatus.Replica.last_update:type_name -> google.protobuf.Timestamp
	12, // 15: control.storage.UpdateStatus.Partition.replicas:type_name -> control.storage.UpdateStatus.Partition.ReplicasEntry
	7,  // 16: control.storage.UpdateStatus.ServersEntry.value:type_name -> control.storage.UpdateStatus.Server
	9,  // 17: control.storage.UpdateStatus.PartitionsEntry.value:type_name -> control.storage.UpdateStatus.Partition
	8,  // 18: control.storage.UpdateStatus.Partition.ReplicasEntry.value:type_name -> control.storage.UpdateStatus.Replica
	19, // 19: control.storage.UpdateAssignments.Update.state:type_name -> control.ReplicaState
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_control_server_storage_storage_proto_init() }
func file_internal_control_server_storage_storage_proto_init() {
	if File_internal_control_server_storage_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_control_server_storage_storage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Bootstrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*InitAssignments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAssignments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Bootstrap_Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateStatus_Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateStatus_Replica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateStatus_Partition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*InitAssignments_Add); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAssignments_Add); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAssignments_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_control_server_storage_storage_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAssignments_Remove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_control_server_storage_storage_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_Bootstrap)(nil),
		(*Command_Register)(nil),
		(*Command_UpdateStatus)(nil),
		(*Command_InitAssignments)(nil),
		(*Command_UpdateAssignments)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_control_server_storage_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_control_server_storage_storage_proto_goTypes,
		DependencyIndexes: file_internal_control_server_storage_storage_proto_depIdxs,
		MessageInfos:      file_internal_control_server_storage_storage_proto_msgTypes,
	}.Build()
	File_internal_control_server_storage_storage_proto = out.File
	file_internal_control_server_storage_storage_proto_rawDesc = nil
	file_internal_control_server_storage_storage_proto_goTypes = nil
	file_internal_control_server_storage_storage_proto_depIdxs = nil
}
