#!/bin/bash
if [ $# -ne 3 ]; then \
    echo "usage: scpx NODE_ID src_path dest_path";
    exit 123;
fi;

scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_rsa $2 root@$(./testing node ip $1):$3
