// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.4
// source: internal/data/common.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnState int32

const (
	TxnState_Pending      TxnState = 0
	TxnState_Prepared     TxnState = 1
	TxnState_Committed    TxnState = 2
	TxnState_Aborted      TxnState = 3
	TxnState_NotFound     TxnState = 4
	TxnState_ActionFailed TxnState = 5
)

// Enum value maps for TxnState.
var (
	TxnState_name = map[int32]string{
		0: "Pending",
		1: "Prepared",
		2: "Committed",
		3: "Aborted",
		4: "NotFound",
		5: "ActionFailed",
	}
	TxnState_value = map[string]int32{
		"Pending":      0,
		"Prepared":     1,
		"Committed":    2,
		"Aborted":      3,
		"NotFound":     4,
		"ActionFailed": 5,
	}
)

func (x TxnState) Enum() *TxnState {
	p := new(TxnState)
	*p = x
	return p
}

func (x TxnState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxnState) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_data_common_proto_enumTypes[0].Descriptor()
}

func (TxnState) Type() protoreflect.EnumType {
	return &file_internal_data_common_proto_enumTypes[0]
}

func (x TxnState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxnState.Descriptor instead.
func (TxnState) EnumDescriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_None             ErrorCode = 0
	ErrorCode_KeyNotFound      ErrorCode = 1
	ErrorCode_KeyAlreadyExists ErrorCode = 2
	ErrorCode_LockCheckFailed  ErrorCode = 3
	ErrorCode_LockFailed       ErrorCode = 4
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "None",
		1: "KeyNotFound",
		2: "KeyAlreadyExists",
		3: "LockCheckFailed",
		4: "LockFailed",
	}
	ErrorCode_value = map[string]int32{
		"None":             0,
		"KeyNotFound":      1,
		"KeyAlreadyExists": 2,
		"LockCheckFailed":  3,
		"LockFailed":       4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_data_common_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_internal_data_common_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{1}
}

type LockKey_Check int32

const (
	LockKey_None         LockKey_Check = 0
	LockKey_MustExist    LockKey_Check = 1
	LockKey_MustNotExist LockKey_Check = 2
)

// Enum value maps for LockKey_Check.
var (
	LockKey_Check_name = map[int32]string{
		0: "None",
		1: "MustExist",
		2: "MustNotExist",
	}
	LockKey_Check_value = map[string]int32{
		"None":         0,
		"MustExist":    1,
		"MustNotExist": 2,
	}
)

func (x LockKey_Check) Enum() *LockKey_Check {
	p := new(LockKey_Check)
	*p = x
	return p
}

func (x LockKey_Check) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockKey_Check) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_data_common_proto_enumTypes[2].Descriptor()
}

func (LockKey_Check) Type() protoreflect.EnumType {
	return &file_internal_data_common_proto_enumTypes[2]
}

func (x LockKey_Check) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockKey_Check.Descriptor instead.
func (LockKey_Check) EnumDescriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{4, 0}
}

type LockRange_Check int32

const (
	LockRange_None           LockRange_Check = 0
	LockRange_MustBeEmpty    LockRange_Check = 1
	LockRange_MustNotBeEmpty LockRange_Check = 2
)

// Enum value maps for LockRange_Check.
var (
	LockRange_Check_name = map[int32]string{
		0: "None",
		1: "MustBeEmpty",
		2: "MustNotBeEmpty",
	}
	LockRange_Check_value = map[string]int32{
		"None":           0,
		"MustBeEmpty":    1,
		"MustNotBeEmpty": 2,
	}
)

func (x LockRange_Check) Enum() *LockRange_Check {
	p := new(LockRange_Check)
	*p = x
	return p
}

func (x LockRange_Check) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockRange_Check) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_data_common_proto_enumTypes[3].Descriptor()
}

func (LockRange_Check) Type() protoreflect.EnumType {
	return &file_internal_data_common_proto_enumTypes[3]
}

func (x LockRange_Check) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockRange_Check.Descriptor instead.
func (LockRange_Check) EnumDescriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{5, 0}
}

type Insert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint64 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Insert) Reset() {
	*x = Insert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insert) ProtoMessage() {}

func (x *Insert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insert.ProtoReflect.Descriptor instead.
func (*Insert) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{0}
}

func (x *Insert) GetKeyspace() uint64 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Insert) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Insert) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint64 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{1}
}

func (x *Update) GetKeyspace() uint64 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Update) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Update) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Upsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint64 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Upsert) Reset() {
	*x = Upsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Upsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upsert) ProtoMessage() {}

func (x *Upsert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upsert.ProtoReflect.Descriptor instead.
func (*Upsert) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{2}
}

func (x *Upsert) GetKeyspace() uint64 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Upsert) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Upsert) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint64 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Delete) Reset() {
	*x = Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{3}
}

func (x *Delete) GetKeyspace() uint64 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Delete) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type LockKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lock  *KeyLock      `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	Check LockKey_Check `protobuf:"varint,2,opt,name=check,proto3,enum=data.LockKey_Check" json:"check,omitempty"`
}

func (x *LockKey) Reset() {
	*x = LockKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockKey) ProtoMessage() {}

func (x *LockKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockKey.ProtoReflect.Descriptor instead.
func (*LockKey) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{4}
}

func (x *LockKey) GetLock() *KeyLock {
	if x != nil {
		return x.Lock
	}
	return nil
}

func (x *LockKey) GetCheck() LockKey_Check {
	if x != nil {
		return x.Check
	}
	return LockKey_None
}

type LockRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lock  *RangeLock      `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	Check LockRange_Check `protobuf:"varint,2,opt,name=check,proto3,enum=data.LockRange_Check" json:"check,omitempty"`
}

func (x *LockRange) Reset() {
	*x = LockRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRange) ProtoMessage() {}

func (x *LockRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRange.ProtoReflect.Descriptor instead.
func (*LockRange) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{5}
}

func (x *LockRange) GetLock() *RangeLock {
	if x != nil {
		return x.Lock
	}
	return nil
}

func (x *LockRange) GetCheck() LockRange_Check {
	if x != nil {
		return x.Check
	}
	return LockRange_None
}

type KeyLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace  uint64 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key       []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Exclusive bool   `protobuf:"varint,3,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
}

func (x *KeyLock) Reset() {
	*x = KeyLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLock) ProtoMessage() {}

func (x *KeyLock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLock.ProtoReflect.Descriptor instead.
func (*KeyLock) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{6}
}

func (x *KeyLock) GetKeyspace() uint64 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *KeyLock) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyLock) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type RangeLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace  uint64 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	StartKey  []byte `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"` // inclusive
	EndKey    []byte `protobuf:"bytes,3,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`       // exclusive
	Exclusive bool   `protobuf:"varint,4,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
}

func (x *RangeLock) Reset() {
	*x = RangeLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeLock) ProtoMessage() {}

func (x *RangeLock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeLock.ProtoReflect.Descriptor instead.
func (*RangeLock) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{7}
}

func (x *RangeLock) GetKeyspace() uint64 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *RangeLock) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RangeLock) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *RangeLock) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*Action_Insert
	//	*Action_Update
	//	*Action_Upsert
	//	*Action_Delete
	//	*Action_LockKey
	//	*Action_LockRange
	Payload isAction_Payload `protobuf_oneof:"payload"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{8}
}

func (m *Action) GetPayload() isAction_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Action) GetInsert() *Insert {
	if x, ok := x.GetPayload().(*Action_Insert); ok {
		return x.Insert
	}
	return nil
}

func (x *Action) GetUpdate() *Update {
	if x, ok := x.GetPayload().(*Action_Update); ok {
		return x.Update
	}
	return nil
}

func (x *Action) GetUpsert() *Upsert {
	if x, ok := x.GetPayload().(*Action_Upsert); ok {
		return x.Upsert
	}
	return nil
}

func (x *Action) GetDelete() *Delete {
	if x, ok := x.GetPayload().(*Action_Delete); ok {
		return x.Delete
	}
	return nil
}

func (x *Action) GetLockKey() *LockKey {
	if x, ok := x.GetPayload().(*Action_LockKey); ok {
		return x.LockKey
	}
	return nil
}

func (x *Action) GetLockRange() *LockRange {
	if x, ok := x.GetPayload().(*Action_LockRange); ok {
		return x.LockRange
	}
	return nil
}

type isAction_Payload interface {
	isAction_Payload()
}

type Action_Insert struct {
	Insert *Insert `protobuf:"bytes,1,opt,name=insert,proto3,oneof"`
}

type Action_Update struct {
	Update *Update `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type Action_Upsert struct {
	Upsert *Upsert `protobuf:"bytes,3,opt,name=upsert,proto3,oneof"`
}

type Action_Delete struct {
	Delete *Delete `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type Action_LockKey struct {
	LockKey *LockKey `protobuf:"bytes,5,opt,name=lock_key,json=lockKey,proto3,oneof"`
}

type Action_LockRange struct {
	LockRange *LockRange `protobuf:"bytes,6,opt,name=lock_range,json=lockRange,proto3,oneof"`
}

func (*Action_Insert) isAction_Payload() {}

func (*Action_Update) isAction_Payload() {}

func (*Action_Upsert) isAction_Payload() {}

func (*Action_Delete) isAction_Payload() {}

func (*Action_LockKey) isAction_Payload() {}

func (*Action_LockRange) isAction_Payload() {}

type TxnId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId  uint64 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TxnId) Reset() {
	*x = TxnId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnId) ProtoMessage() {}

func (x *TxnId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnId.ProtoReflect.Descriptor instead.
func (*TxnId) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{9}
}

func (x *TxnId) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *TxnId) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Txn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *TxnId    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actions []*Action `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *Txn) Reset() {
	*x = Txn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txn) ProtoMessage() {}

func (x *Txn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txn.ProtoReflect.Descriptor instead.
func (*Txn) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{10}
}

func (x *Txn) GetId() *TxnId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Txn) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type TxnStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *TxnId    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp   uint64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	State       TxnState  `protobuf:"varint,3,opt,name=state,proto3,enum=data.TxnState" json:"state,omitempty"`
	ActionIndex uint32    `protobuf:"varint,4,opt,name=action_index,json=actionIndex,proto3" json:"action_index,omitempty"`                     // only for ActionFailed state; the failed action index
	ActionError ErrorCode `protobuf:"varint,5,opt,name=action_error,json=actionError,proto3,enum=data.ErrorCode" json:"action_error,omitempty"` // only for ActionFailed state; the failed action error code
}

func (x *TxnStatus) Reset() {
	*x = TxnStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnStatus) ProtoMessage() {}

func (x *TxnStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnStatus.ProtoReflect.Descriptor instead.
func (*TxnStatus) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{11}
}

func (x *TxnStatus) GetId() *TxnId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TxnStatus) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TxnStatus) GetState() TxnState {
	if x != nil {
		return x.State
	}
	return TxnState_Pending
}

func (x *TxnStatus) GetActionIndex() uint32 {
	if x != nil {
		return x.ActionIndex
	}
	return 0
}

func (x *TxnStatus) GetActionError() ErrorCode {
	if x != nil {
		return x.ActionError
	}
	return ErrorCode_None
}

type TxnBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionId     uint32   `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Autocommit      []*Txn   `protobuf:"bytes,2,rep,name=autocommit,proto3" json:"autocommit,omitempty"`
	TwoPhasePrepare []*Txn   `protobuf:"bytes,3,rep,name=two_phase_prepare,json=twoPhasePrepare,proto3" json:"two_phase_prepare,omitempty"`
	TwoPhaseCommit  []*TxnId `protobuf:"bytes,4,rep,name=two_phase_commit,json=twoPhaseCommit,proto3" json:"two_phase_commit,omitempty"`
	TwoPhaseAbort   []*TxnId `protobuf:"bytes,5,rep,name=two_phase_abort,json=twoPhaseAbort,proto3" json:"two_phase_abort,omitempty"`
}

func (x *TxnBatch) Reset() {
	*x = TxnBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnBatch) ProtoMessage() {}

func (x *TxnBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnBatch.ProtoReflect.Descriptor instead.
func (*TxnBatch) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{12}
}

func (x *TxnBatch) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *TxnBatch) GetAutocommit() []*Txn {
	if x != nil {
		return x.Autocommit
	}
	return nil
}

func (x *TxnBatch) GetTwoPhasePrepare() []*Txn {
	if x != nil {
		return x.TwoPhasePrepare
	}
	return nil
}

func (x *TxnBatch) GetTwoPhaseCommit() []*TxnId {
	if x != nil {
		return x.TwoPhaseCommit
	}
	return nil
}

func (x *TxnBatch) GetTwoPhaseAbort() []*TxnId {
	if x != nil {
		return x.TwoPhaseAbort
	}
	return nil
}

type TxnBatchStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status []*TxnStatus `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
}

func (x *TxnBatchStatus) Reset() {
	*x = TxnBatchStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnBatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnBatchStatus) ProtoMessage() {}

func (x *TxnBatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnBatchStatus.ProtoReflect.Descriptor instead.
func (*TxnBatchStatus) Descriptor() ([]byte, []int) {
	return file_internal_data_common_proto_rawDescGZIP(), []int{13}
}

func (x *TxnBatchStatus) GetStatus() []*TxnStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_internal_data_common_proto protoreflect.FileDescriptor

var file_internal_data_common_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4c, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x4c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65,
	0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6b, 0x65,
	0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c,
	0x0a, 0x06, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x4c, 0x6f, 0x63, 0x6b, 0x4b, 0x65, 0x79,
	0x12, 0x21, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x04, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x29, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x4b, 0x65,
	0x79, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x32,
	0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x75, 0x73, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x75, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x10, 0x02, 0x22, 0x95, 0x01, 0x0a, 0x09, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x52,
	0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2b, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x63, 0x6b,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x05, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x22, 0x36, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x75, 0x73, 0x74, 0x42, 0x65, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x75, 0x73, 0x74, 0x4e, 0x6f,
	0x74, 0x42, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x02, 0x22, 0x55, 0x0a, 0x07, 0x4b, 0x65,
	0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76,
	0x65, 0x22, 0x7b, 0x0a, 0x09, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1a,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22, 0x91,
	0x02, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x06, 0x69, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x12, 0x26, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48,
	0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x75, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x12, 0x26, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48,
	0x00, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x07, 0x6c, 0x6f,
	0x63, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x30, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x42, 0x0a, 0x05, 0x54, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x4a, 0x0a, 0x03, 0x54, 0x78, 0x6e, 0x12, 0x1b, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x54, 0x78, 0x6e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0xc3, 0x01, 0x0a, 0x09, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x54, 0x78, 0x6e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x24, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x32, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xfb, 0x01, 0x0a, 0x08, 0x54, 0x78, 0x6e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x12, 0x35, 0x0a, 0x11, 0x74, 0x77, 0x6f, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65,
	0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x0f, 0x74, 0x77, 0x6f, 0x50, 0x68,
	0x61, 0x73, 0x65, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x35, 0x0a, 0x10, 0x74, 0x77,
	0x6f, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x78, 0x6e, 0x49,
	0x64, 0x52, 0x0e, 0x74, 0x77, 0x6f, 0x50, 0x68, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x12, 0x33, 0x0a, 0x0f, 0x74, 0x77, 0x6f, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x61,
	0x62, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x54, 0x78, 0x6e, 0x49, 0x64, 0x52, 0x0d, 0x74, 0x77, 0x6f, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x22, 0x39, 0x0a, 0x0e, 0x54, 0x78, 0x6e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2a, 0x61, 0x0a, 0x08, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x62, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64,
	0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x10, 0x05, 0x2a, 0x61, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4b,
	0x65, 0x79, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10,
	0x4b, 0x65, 0x79, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x6b, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x04, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x63, 0x72, 0x75, 0x73, 0x75, 0x2f, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_data_common_proto_rawDescOnce sync.Once
	file_internal_data_common_proto_rawDescData = file_internal_data_common_proto_rawDesc
)

func file_internal_data_common_proto_rawDescGZIP() []byte {
	file_internal_data_common_proto_rawDescOnce.Do(func() {
		file_internal_data_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_data_common_proto_rawDescData)
	})
	return file_internal_data_common_proto_rawDescData
}

var file_internal_data_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_internal_data_common_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_data_common_proto_goTypes = []any{
	(TxnState)(0),          // 0: data.TxnState
	(ErrorCode)(0),         // 1: data.ErrorCode
	(LockKey_Check)(0),     // 2: data.LockKey.Check
	(LockRange_Check)(0),   // 3: data.LockRange.Check
	(*Insert)(nil),         // 4: data.Insert
	(*Update)(nil),         // 5: data.Update
	(*Upsert)(nil),         // 6: data.Upsert
	(*Delete)(nil),         // 7: data.Delete
	(*LockKey)(nil),        // 8: data.LockKey
	(*LockRange)(nil),      // 9: data.LockRange
	(*KeyLock)(nil),        // 10: data.KeyLock
	(*RangeLock)(nil),      // 11: data.RangeLock
	(*Action)(nil),         // 12: data.Action
	(*TxnId)(nil),          // 13: data.TxnId
	(*Txn)(nil),            // 14: data.Txn
	(*TxnStatus)(nil),      // 15: data.TxnStatus
	(*TxnBatch)(nil),       // 16: data.TxnBatch
	(*TxnBatchStatus)(nil), // 17: data.TxnBatchStatus
}
var file_internal_data_common_proto_depIdxs = []int32{
	10, // 0: data.LockKey.lock:type_name -> data.KeyLock
	2,  // 1: data.LockKey.check:type_name -> data.LockKey.Check
	11, // 2: data.LockRange.lock:type_name -> data.RangeLock
	3,  // 3: data.LockRange.check:type_name -> data.LockRange.Check
	4,  // 4: data.Action.insert:type_name -> data.Insert
	5,  // 5: data.Action.update:type_name -> data.Update
	6,  // 6: data.Action.upsert:type_name -> data.Upsert
	7,  // 7: data.Action.delete:type_name -> data.Delete
	8,  // 8: data.Action.lock_key:type_name -> data.LockKey
	9,  // 9: data.Action.lock_range:type_name -> data.LockRange
	13, // 10: data.Txn.id:type_name -> data.TxnId
	12, // 11: data.Txn.actions:type_name -> data.Action
	13, // 12: data.TxnStatus.id:type_name -> data.TxnId
	0,  // 13: data.TxnStatus.state:type_name -> data.TxnState
	1,  // 14: data.TxnStatus.action_error:type_name -> data.ErrorCode
	14, // 15: data.TxnBatch.autocommit:type_name -> data.Txn
	14, // 16: data.TxnBatch.two_phase_prepare:type_name -> data.Txn
	13, // 17: data.TxnBatch.two_phase_commit:type_name -> data.TxnId
	13, // 18: data.TxnBatch.two_phase_abort:type_name -> data.TxnId
	15, // 19: data.TxnBatchStatus.status:type_name -> data.TxnStatus
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_data_common_proto_init() }
func file_internal_data_common_proto_init() {
	if File_internal_data_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_data_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Insert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Upsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LockKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LockRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*KeyLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RangeLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*TxnId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Txn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*TxnStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*TxnBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_common_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*TxnBatchStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_data_common_proto_msgTypes[8].OneofWrappers = []any{
		(*Action_Insert)(nil),
		(*Action_Update)(nil),
		(*Action_Upsert)(nil),
		(*Action_Delete)(nil),
		(*Action_LockKey)(nil),
		(*Action_LockRange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_data_common_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_data_common_proto_goTypes,
		DependencyIndexes: file_internal_data_common_proto_depIdxs,
		EnumInfos:         file_internal_data_common_proto_enumTypes,
		MessageInfos:      file_internal_data_common_proto_msgTypes,
	}.Build()
	File_internal_data_common_proto = out.File
	file_internal_data_common_proto_rawDesc = nil
	file_internal_data_common_proto_goTypes = nil
	file_internal_data_common_proto_depIdxs = nil
}
