# Config options are defined in github.com/bcrusu/scouot/internal/control/server/config/config.go

clusterName: demo
dataDir: /scout/storage/
bootstrap:
  initialServers:
    - address: control1
    - address: control2
    - address: control3
  partitionCount: 100
partitions:
  replicationFactor: 3
logLevels: "*:info,hraft:error,rpc_logger:error"
metrics:
  exportEndpoint: otelcol:4317
