user nginx;
events {
 worker_connections 1000;
}
http {
 upstream scout_api {
   server api:11001;
 }
 server {
   listen 11001;
   http2 on;
   access_log off;
   location / {
     grpc_pass grpc://scout_api;
   }
 }
}
