{
 "title": "Data",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server",
    "query": {
     "query": "label_values({server_type=\"data\"},server_name)"
    }
   },
   {
    "name": "rpc_service",
    "label": "Service",
    "query": {
     "query": "query_result(rpc_server_started_total * on (job) group_left (server_name) target_info {server_type=\"data\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "RPC requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_started_total{rpc_service=~\"$rpc_service\"}[$__rate_interval])\n* on (job) group_left (server_name)\ntarget_info{server_type=\"data\",server_name=~\"$server_name\"}) by(rpc_service, rpc_method)",
     "legendFormat": "Total.{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(rpc_server_completed_total{rpc_service=~\"$rpc_service\",rpc_status_code!=\"OK\"}[$__rate_interval])\n* on (job) group_left (server_name)\ntarget_info{server_type=\"data\",server_name=~\"$server_name\"}",
     "legendFormat": "Total.{{rpc_method}}"
    }
   ]
  },
  {
   "title": "Duration p.99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum by(le, rpc_service, rpc_method)\n(rate(rpc_server_duration_bucket{rpc_service=~\"$rpc_service\"}[$__rate_interval])\n* on (job) group_left (server_name)\ntarget_info{server_type=\"data\",server_name=~\"$server_name\"}))",
     "legendFormat": "{{rpc_method}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Transaction rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(txn_rw_autocommitted_total[$__rate_interval])\n* on (job) group_left (server_name)\ntarget_info{server_type=\"data\",server_name=~\"$server_name\"}",
     "legendFormat": "Autocommitted"
    },
    {
     "expr": "rate(txn_rw_timedout_total[$__rate_interval])",
     "legendFormat": "Aborted {{job}}"
    }
   ]
  },
  {
   "title": "Transactions tracked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "txn_ro_prepared", "legendFormat": "Prepared read-only {{job}}" },
    { "expr": "txn_rw_tracked", "legendFormat": "Tracked read-write {{job}}" },
    { "expr": "txn_rw_running", "legendFormat": "Running 2PC {{job}}" }
   ]
  }
 ]
}