// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.4
// source: internal/data/server/txn/txn.proto

package txn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status_State int32

const (
	Status_Pending   Status_State = 0
	Status_Prepared  Status_State = 1
	Status_Committed Status_State = 2
	Status_Aborted   Status_State = 3
	Status_Failed    Status_State = 4
	Status_Timedout  Status_State = 5
	Status_Decided   Status_State = 6
)

// Enum value maps for Status_State.
var (
	Status_State_name = map[int32]string{
		0: "Pending",
		1: "Prepared",
		2: "Committed",
		3: "Aborted",
		4: "Failed",
		5: "Timedout",
		6: "Decided",
	}
	Status_State_value = map[string]int32{
		"Pending":   0,
		"Prepared":  1,
		"Committed": 2,
		"Aborted":   3,
		"Failed":    4,
		"Timedout":  5,
		"Decided":   6,
	}
)

func (x Status_State) Enum() *Status_State {
	p := new(Status_State)
	*p = x
	return p
}

func (x Status_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_State) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_data_server_txn_txn_proto_enumTypes[0].Descriptor()
}

func (Status_State) Type() protoreflect.EnumType {
	return &file_internal_data_server_txn_txn_proto_enumTypes[0]
}

func (x Status_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_State.Descriptor instead.
func (Status_State) EnumDescriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{10, 0}
}

type LockKey_Check int32

const (
	LockKey_None         LockKey_Check = 0
	LockKey_MustExist    LockKey_Check = 1
	LockKey_MustNotExist LockKey_Check = 2
)

// Enum value maps for LockKey_Check.
var (
	LockKey_Check_name = map[int32]string{
		0: "None",
		1: "MustExist",
		2: "MustNotExist",
	}
	LockKey_Check_value = map[string]int32{
		"None":         0,
		"MustExist":    1,
		"MustNotExist": 2,
	}
)

func (x LockKey_Check) Enum() *LockKey_Check {
	p := new(LockKey_Check)
	*p = x
	return p
}

func (x LockKey_Check) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockKey_Check) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_data_server_txn_txn_proto_enumTypes[1].Descriptor()
}

func (LockKey_Check) Type() protoreflect.EnumType {
	return &file_internal_data_server_txn_txn_proto_enumTypes[1]
}

func (x LockKey_Check) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockKey_Check.Descriptor instead.
func (LockKey_Check) EnumDescriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{17, 0}
}

type LockRange_Check int32

const (
	LockRange_None           LockRange_Check = 0
	LockRange_MustBeEmpty    LockRange_Check = 1
	LockRange_MustNotBeEmpty LockRange_Check = 2
)

// Enum value maps for LockRange_Check.
var (
	LockRange_Check_name = map[int32]string{
		0: "None",
		1: "MustBeEmpty",
		2: "MustNotBeEmpty",
	}
	LockRange_Check_value = map[string]int32{
		"None":           0,
		"MustBeEmpty":    1,
		"MustNotBeEmpty": 2,
	}
)

func (x LockRange_Check) Enum() *LockRange_Check {
	p := new(LockRange_Check)
	*p = x
	return p
}

func (x LockRange_Check) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockRange_Check) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_data_server_txn_txn_proto_enumTypes[2].Descriptor()
}

func (LockRange_Check) Type() protoreflect.EnumType {
	return &file_internal_data_server_txn_txn_proto_enumTypes[2]
}

func (x LockRange_Check) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockRange_Check.Descriptor instead.
func (LockRange_Check) EnumDescriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{18, 0}
}

type ActionStatus_Code int32

const (
	ActionStatus_Success          ActionStatus_Code = 0
	ActionStatus_KeyNotFound      ActionStatus_Code = 1
	ActionStatus_KeyAlreadyExists ActionStatus_Code = 2
	ActionStatus_LockCheckFailed  ActionStatus_Code = 3
	ActionStatus_LockFailed       ActionStatus_Code = 4
	ActionStatus_CorruptedData    ActionStatus_Code = 5
)

// Enum value maps for ActionStatus_Code.
var (
	ActionStatus_Code_name = map[int32]string{
		0: "Success",
		1: "KeyNotFound",
		2: "KeyAlreadyExists",
		3: "LockCheckFailed",
		4: "LockFailed",
		5: "CorruptedData",
	}
	ActionStatus_Code_value = map[string]int32{
		"Success":          0,
		"KeyNotFound":      1,
		"KeyAlreadyExists": 2,
		"LockCheckFailed":  3,
		"LockFailed":       4,
		"CorruptedData":    5,
	}
)

func (x ActionStatus_Code) Enum() *ActionStatus_Code {
	p := new(ActionStatus_Code)
	*p = x
	return p
}

func (x ActionStatus_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionStatus_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_data_server_txn_txn_proto_enumTypes[3].Descriptor()
}

func (ActionStatus_Code) Type() protoreflect.EnumType {
	return &file_internal_data_server_txn_txn_proto_enumTypes[3]
}

func (x ActionStatus_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionStatus_Code.Descriptor instead.
func (ActionStatus_Code) EnumDescriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{24, 0}
}

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       []*Status   `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	Prepared     []*Prepared `protobuf:"bytes,2,rep,name=prepared,proto3" json:"prepared,omitempty"`
	MaxTimestamp uint64      `protobuf:"varint,3,opt,name=max_timestamp,json=maxTimestamp,proto3" json:"max_timestamp,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetStatus() []*Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Snapshot) GetPrepared() []*Prepared {
	if x != nil {
		return x.Prepared
	}
	return nil
}

func (x *Snapshot) GetMaxTimestamp() uint64 {
	if x != nil {
		return x.MaxTimestamp
	}
	return 0
}

type Autocommit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Txn       *Txn   `protobuf:"bytes,2,opt,name=txn,proto3" json:"txn,omitempty"`
}

func (x *Autocommit) Reset() {
	*x = Autocommit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Autocommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Autocommit) ProtoMessage() {}

func (x *Autocommit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Autocommit.ProtoReflect.Descriptor instead.
func (*Autocommit) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{1}
}

func (x *Autocommit) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Autocommit) GetTxn() *Txn {
	if x != nil {
		return x.Txn
	}
	return nil
}

type Prepare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Txn       *Txn   `protobuf:"bytes,2,opt,name=txn,proto3" json:"txn,omitempty"`
}

func (x *Prepare) Reset() {
	*x = Prepare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare) ProtoMessage() {}

func (x *Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare.ProtoReflect.Descriptor instead.
func (*Prepare) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{2}
}

func (x *Prepare) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Prepare) GetTxn() *Txn {
	if x != nil {
		return x.Txn
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id        *Id    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Commit) Reset() {
	*x = Commit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{3}
}

func (x *Commit) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Commit) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

type Abort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id        *Id    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Abort) Reset() {
	*x = Abort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Abort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Abort) ProtoMessage() {}

func (x *Abort) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Abort.ProtoReflect.Descriptor instead.
func (*Abort) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{4}
}

func (x *Abort) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Abort) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

type StoreDecision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Decision  *Decision `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
}

func (x *StoreDecision) Reset() {
	*x = StoreDecision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDecision) ProtoMessage() {}

func (x *StoreDecision) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDecision.ProtoReflect.Descriptor instead.
func (*StoreDecision) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{5}
}

func (x *StoreDecision) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StoreDecision) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

// The watchdog will apply the command twice for each timedout txn
// and the second will release the locks, completing the 2pc process.
type MarkTimedout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp    uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id           *Id    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ReleaseLocks bool   `protobuf:"varint,3,opt,name=release_locks,json=releaseLocks,proto3" json:"release_locks,omitempty"`
}

func (x *MarkTimedout) Reset() {
	*x = MarkTimedout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkTimedout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTimedout) ProtoMessage() {}

func (x *MarkTimedout) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTimedout.ProtoReflect.Descriptor instead.
func (*MarkTimedout) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{6}
}

func (x *MarkTimedout) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MarkTimedout) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MarkTimedout) GetReleaseLocks() bool {
	if x != nil {
		return x.ReleaseLocks
	}
	return false
}

type Batch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Autocommit    []*Autocommit    `protobuf:"bytes,1,rep,name=autocommit,proto3" json:"autocommit,omitempty"`
	Prepare       []*Prepare       `protobuf:"bytes,2,rep,name=prepare,proto3" json:"prepare,omitempty"`
	Commit        []*Commit        `protobuf:"bytes,3,rep,name=commit,proto3" json:"commit,omitempty"`
	Abort         []*Abort         `protobuf:"bytes,4,rep,name=abort,proto3" json:"abort,omitempty"`
	StoreDecision []*StoreDecision `protobuf:"bytes,5,rep,name=store_decision,json=storeDecision,proto3" json:"store_decision,omitempty"`
	MarkTimedout  []*MarkTimedout  `protobuf:"bytes,6,rep,name=mark_timedout,json=markTimedout,proto3" json:"mark_timedout,omitempty"`
}

func (x *Batch) Reset() {
	*x = Batch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{7}
}

func (x *Batch) GetAutocommit() []*Autocommit {
	if x != nil {
		return x.Autocommit
	}
	return nil
}

func (x *Batch) GetPrepare() []*Prepare {
	if x != nil {
		return x.Prepare
	}
	return nil
}

func (x *Batch) GetCommit() []*Commit {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *Batch) GetAbort() []*Abort {
	if x != nil {
		return x.Abort
	}
	return nil
}

func (x *Batch) GetStoreDecision() []*StoreDecision {
	if x != nil {
		return x.StoreDecision
	}
	return nil
}

func (x *Batch) GetMarkTimedout() []*MarkTimedout {
	if x != nil {
		return x.MarkTimedout
	}
	return nil
}

// Id uniquely identifies a transaction in the cluster.
type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The principal partition is where the txn status is written.
	// For a single-partition/autocommit txn, it corresponds to the
	// the sole partition involved in the transaction.
	// For a two-phase commit txn, a participant partition is selected
	// to act as a secondary coordinator and holds the overall txn status.
	PrincipalPid uint32 `protobuf:"varint,1,opt,name=principal_pid,json=principalPid,proto3" json:"principal_pid,omitempty"`
	// Originating server identifier.
	ServerId uint64 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Originating server HLC from when txn is created. It acts as
	// a unique identifier and differs from the commit timestamp found
	// in Status which is decided by the participants.
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{8}
}

func (x *Id) GetPrincipalPid() uint32 {
	if x != nil {
		return x.PrincipalPid
	}
	return 0
}

func (x *Id) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Id) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Txn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *Id       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actions []*Action `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	// used only for 2PC txn and sent only to the principal partition.
	ParticipantPids []uint32 `protobuf:"varint,3,rep,packed,name=participant_pids,json=participantPids,proto3" json:"participant_pids,omitempty"`
}

func (x *Txn) Reset() {
	*x = Txn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txn) ProtoMessage() {}

func (x *Txn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txn.ProtoReflect.Descriptor instead.
func (*Txn) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{9}
}

func (x *Txn) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Txn) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Txn) GetParticipantPids() []uint32 {
	if x != nil {
		return x.ParticipantPids
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              *Id                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp       uint64                   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	State           Status_State             `protobuf:"varint,3,opt,name=state,proto3,enum=txn.Status_State" json:"state,omitempty"`
	ActionStatus    map[uint32]*ActionStatus `protobuf:"bytes,4,rep,name=action_status,json=actionStatus,proto3" json:"action_status,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ParticipantPids []uint32                 `protobuf:"varint,5,rep,packed,name=participant_pids,json=participantPids,proto3" json:"participant_pids,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{10}
}

func (x *Status) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Status) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Status) GetState() Status_State {
	if x != nil {
		return x.State
	}
	return Status_Pending
}

func (x *Status) GetActionStatus() map[uint32]*ActionStatus {
	if x != nil {
		return x.ActionStatus
	}
	return nil
}

func (x *Status) GetParticipantPids() []uint32 {
	if x != nil {
		return x.ParticipantPids
	}
	return nil
}

type Insert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint32 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Insert) Reset() {
	*x = Insert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insert) ProtoMessage() {}

func (x *Insert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insert.ProtoReflect.Descriptor instead.
func (*Insert) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{11}
}

func (x *Insert) GetKeyspace() uint32 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Insert) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Insert) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint32 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{12}
}

func (x *Update) GetKeyspace() uint32 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Update) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Update) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Upsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint32 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Upsert) Reset() {
	*x = Upsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Upsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upsert) ProtoMessage() {}

func (x *Upsert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upsert.ProtoReflect.Descriptor instead.
func (*Upsert) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{13}
}

func (x *Upsert) GetKeyspace() uint32 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Upsert) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Upsert) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Delete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint32 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Delete) Reset() {
	*x = Delete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{14}
}

func (x *Delete) GetKeyspace() uint32 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Delete) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Read struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace uint32 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key      []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Read) Reset() {
	*x = Read{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{15}
}

func (x *Read) GetKeyspace() uint32 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *Read) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ReadRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace   uint32 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	StartKey   []byte `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"` // inclusive
	EndKey     []byte `protobuf:"bytes,3,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`       // exclusive
	MaxResults uint32 `protobuf:"varint,4,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
}

func (x *ReadRange) Reset() {
	*x = ReadRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRange) ProtoMessage() {}

func (x *ReadRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRange.ProtoReflect.Descriptor instead.
func (*ReadRange) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{16}
}

func (x *ReadRange) GetKeyspace() uint32 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *ReadRange) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *ReadRange) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *ReadRange) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type LockKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lock  *KeyLock      `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	Check LockKey_Check `protobuf:"varint,2,opt,name=check,proto3,enum=txn.LockKey_Check" json:"check,omitempty"`
}

func (x *LockKey) Reset() {
	*x = LockKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockKey) ProtoMessage() {}

func (x *LockKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockKey.ProtoReflect.Descriptor instead.
func (*LockKey) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{17}
}

func (x *LockKey) GetLock() *KeyLock {
	if x != nil {
		return x.Lock
	}
	return nil
}

func (x *LockKey) GetCheck() LockKey_Check {
	if x != nil {
		return x.Check
	}
	return LockKey_None
}

type LockRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lock  *RangeLock      `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	Check LockRange_Check `protobuf:"varint,2,opt,name=check,proto3,enum=txn.LockRange_Check" json:"check,omitempty"`
}

func (x *LockRange) Reset() {
	*x = LockRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRange) ProtoMessage() {}

func (x *LockRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRange.ProtoReflect.Descriptor instead.
func (*LockRange) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{18}
}

func (x *LockRange) GetLock() *RangeLock {
	if x != nil {
		return x.Lock
	}
	return nil
}

func (x *LockRange) GetCheck() LockRange_Check {
	if x != nil {
		return x.Check
	}
	return LockRange_None
}

type KeyLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace  uint32 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Key       []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Exclusive bool   `protobuf:"varint,3,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
}

func (x *KeyLock) Reset() {
	*x = KeyLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLock) ProtoMessage() {}

func (x *KeyLock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLock.ProtoReflect.Descriptor instead.
func (*KeyLock) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{19}
}

func (x *KeyLock) GetKeyspace() uint32 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *KeyLock) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyLock) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type RangeLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyspace  uint32 `protobuf:"varint,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	StartKey  []byte `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"` // inclusive
	EndKey    []byte `protobuf:"bytes,3,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`       // exclusive
	Exclusive bool   `protobuf:"varint,4,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
}

func (x *RangeLock) Reset() {
	*x = RangeLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeLock) ProtoMessage() {}

func (x *RangeLock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeLock.ProtoReflect.Descriptor instead.
func (*RangeLock) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{20}
}

func (x *RangeLock) GetKeyspace() uint32 {
	if x != nil {
		return x.Keyspace
	}
	return 0
}

func (x *RangeLock) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RangeLock) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *RangeLock) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Action_Read
	//	*Action_ReadRange
	//	*Action_Insert
	//	*Action_Update
	//	*Action_Upsert
	//	*Action_Delete
	//	*Action_LockKey
	//	*Action_LockRange
	Payload isAction_Payload `protobuf_oneof:"payload"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{21}
}

func (x *Action) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (m *Action) GetPayload() isAction_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Action) GetRead() *Read {
	if x, ok := x.GetPayload().(*Action_Read); ok {
		return x.Read
	}
	return nil
}

func (x *Action) GetReadRange() *ReadRange {
	if x, ok := x.GetPayload().(*Action_ReadRange); ok {
		return x.ReadRange
	}
	return nil
}

func (x *Action) GetInsert() *Insert {
	if x, ok := x.GetPayload().(*Action_Insert); ok {
		return x.Insert
	}
	return nil
}

func (x *Action) GetUpdate() *Update {
	if x, ok := x.GetPayload().(*Action_Update); ok {
		return x.Update
	}
	return nil
}

func (x *Action) GetUpsert() *Upsert {
	if x, ok := x.GetPayload().(*Action_Upsert); ok {
		return x.Upsert
	}
	return nil
}

func (x *Action) GetDelete() *Delete {
	if x, ok := x.GetPayload().(*Action_Delete); ok {
		return x.Delete
	}
	return nil
}

func (x *Action) GetLockKey() *LockKey {
	if x, ok := x.GetPayload().(*Action_LockKey); ok {
		return x.LockKey
	}
	return nil
}

func (x *Action) GetLockRange() *LockRange {
	if x, ok := x.GetPayload().(*Action_LockRange); ok {
		return x.LockRange
	}
	return nil
}

type isAction_Payload interface {
	isAction_Payload()
}

type Action_Read struct {
	Read *Read `protobuf:"bytes,2,opt,name=read,proto3,oneof"`
}

type Action_ReadRange struct {
	ReadRange *ReadRange `protobuf:"bytes,3,opt,name=read_range,json=readRange,proto3,oneof"`
}

type Action_Insert struct {
	Insert *Insert `protobuf:"bytes,4,opt,name=insert,proto3,oneof"`
}

type Action_Update struct {
	Update *Update `protobuf:"bytes,5,opt,name=update,proto3,oneof"`
}

type Action_Upsert struct {
	Upsert *Upsert `protobuf:"bytes,6,opt,name=upsert,proto3,oneof"`
}

type Action_Delete struct {
	Delete *Delete `protobuf:"bytes,7,opt,name=delete,proto3,oneof"`
}

type Action_LockKey struct {
	LockKey *LockKey `protobuf:"bytes,8,opt,name=lock_key,json=lockKey,proto3,oneof"`
}

type Action_LockRange struct {
	LockRange *LockRange `protobuf:"bytes,9,opt,name=lock_range,json=lockRange,proto3,oneof"`
}

func (*Action_Read) isAction_Payload() {}

func (*Action_ReadRange) isAction_Payload() {}

func (*Action_Insert) isAction_Payload() {}

func (*Action_Update) isAction_Payload() {}

func (*Action_Upsert) isAction_Payload() {}

func (*Action_Delete) isAction_Payload() {}

func (*Action_LockKey) isAction_Payload() {}

func (*Action_LockRange) isAction_Payload() {}

type Lock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionId uint32 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Lock_KeyLock
	//	*Lock_RangeLock
	Payload isLock_Payload `protobuf_oneof:"payload"`
}

func (x *Lock) Reset() {
	*x = Lock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{22}
}

func (x *Lock) GetActionId() uint32 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (m *Lock) GetPayload() isLock_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Lock) GetKeyLock() *KeyLock {
	if x, ok := x.GetPayload().(*Lock_KeyLock); ok {
		return x.KeyLock
	}
	return nil
}

func (x *Lock) GetRangeLock() *RangeLock {
	if x, ok := x.GetPayload().(*Lock_RangeLock); ok {
		return x.RangeLock
	}
	return nil
}

type isLock_Payload interface {
	isLock_Payload()
}

type Lock_KeyLock struct {
	KeyLock *KeyLock `protobuf:"bytes,2,opt,name=key_lock,json=keyLock,proto3,oneof"`
}

type Lock_RangeLock struct {
	RangeLock *RangeLock `protobuf:"bytes,3,opt,name=range_lock,json=rangeLock,proto3,oneof"`
}

func (*Lock_KeyLock) isLock_Payload() {}

func (*Lock_RangeLock) isLock_Payload() {}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*Value_Bytes
	Payload isValue_Payload `protobuf_oneof:"payload"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{23}
}

func (m *Value) GetPayload() isValue_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Value) GetBytes() []byte {
	if x, ok := x.GetPayload().(*Value_Bytes); ok {
		return x.Bytes
	}
	return nil
}

type isValue_Payload interface {
	isValue_Payload()
}

type Value_Bytes struct {
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3,oneof"`
}

func (*Value_Bytes) isValue_Payload() {}

type ActionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code    ActionStatus_Code `protobuf:"varint,2,opt,name=code,proto3,enum=txn.ActionStatus_Code" json:"code,omitempty"`
	Results []*Value          `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ActionStatus) Reset() {
	*x = ActionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionStatus) ProtoMessage() {}

func (x *ActionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionStatus.ProtoReflect.Descriptor instead.
func (*ActionStatus) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{24}
}

func (x *ActionStatus) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActionStatus) GetCode() ActionStatus_Code {
	if x != nil {
		return x.Code
	}
	return ActionStatus_Success
}

func (x *ActionStatus) GetResults() []*Value {
	if x != nil {
		return x.Results
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              *Id    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Commit          bool   `protobuf:"varint,2,opt,name=commit,proto3" json:"commit,omitempty"`
	CommitTimestamp uint64 `protobuf:"varint,3,opt,name=commit_timestamp,json=commitTimestamp,proto3" json:"commit_timestamp,omitempty"`
}

func (x *Decision) Reset() {
	*x = Decision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{25}
}

func (x *Decision) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Decision) GetCommit() bool {
	if x != nil {
		return x.Commit
	}
	return false
}

func (x *Decision) GetCommitTimestamp() uint64 {
	if x != nil {
		return x.CommitTimestamp
	}
	return 0
}

type Prepared struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txn           *Txn      `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Locks         []*Lock   `protobuf:"bytes,2,rep,name=locks,proto3" json:"locks,omitempty"`
	LocksReleased bool      `protobuf:"varint,3,opt,name=locks_released,json=locksReleased,proto3" json:"locks_released,omitempty"`
	Decision      *Decision `protobuf:"bytes,4,opt,name=decision,proto3" json:"decision,omitempty"`
}

func (x *Prepared) Reset() {
	*x = Prepared{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_txn_txn_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prepared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepared) ProtoMessage() {}

func (x *Prepared) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_txn_txn_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepared.ProtoReflect.Descriptor instead.
func (*Prepared) Descriptor() ([]byte, []int) {
	return file_internal_data_server_txn_txn_proto_rawDescGZIP(), []int{26}
}

func (x *Prepared) GetTxn() *Txn {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *Prepared) GetLocks() []*Lock {
	if x != nil {
		return x.Locks
	}
	return nil
}

func (x *Prepared) GetLocksReleased() bool {
	if x != nil {
		return x.LocksReleased
	}
	return false
}

func (x *Prepared) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

var File_internal_data_server_txn_txn_proto protoreflect.FileDescriptor

var file_internal_data_server_txn_txn_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x78, 0x6e, 0x2f, 0x74, 0x78, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x78, 0x6e, 0x22, 0x7f, 0x0a, 0x08, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74,
	0x78, 0x6e, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x52, 0x08, 0x70, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6d, 0x61,
	0x78, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x46, 0x0a, 0x0a, 0x41, 0x75,
	0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x03, 0x74, 0x78, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x03, 0x74,
	0x78, 0x6e, 0x22, 0x43, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x03, 0x74,
	0x78, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x54,
	0x78, 0x6e, 0x52, 0x03, 0x74, 0x78, 0x6e, 0x22, 0x3f, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x74, 0x78,
	0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x05, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x74, 0x78,
	0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x29, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x78, 0x6e, 0x2e,
	0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x6a, 0x0a, 0x0c, 0x4d, 0x61, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x6f,
	0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x74,
	0x78, 0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x9a,
	0x02, 0x0a, 0x05, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x2f, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x6f,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74,
	0x78, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x0a, 0x61,
	0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x07, 0x70, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x78, 0x6e,
	0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x07, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x12, 0x23, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x61, 0x62, 0x6f, 0x72, 0x74, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x52, 0x05, 0x61, 0x62, 0x6f, 0x72, 0x74, 0x12, 0x39, 0x0a, 0x0e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x5f, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x0d, 0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x64, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x78, 0x6e,
	0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x6f, 0x75, 0x74, 0x52, 0x0c, 0x6d,
	0x61, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x6f, 0x75, 0x74, 0x22, 0x64, 0x0a, 0x02, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x5f, 0x70,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69,
	0x70, 0x61, 0x6c, 0x50, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x70, 0x0a, 0x03, 0x54, 0x78, 0x6e, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x25, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x5f, 0x70, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x50,
	0x69, 0x64, 0x73, 0x22, 0x92, 0x03, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x74, 0x78, 0x6e,
	0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x42,
	0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x5f, 0x70, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x50, 0x69, 0x64, 0x73, 0x1a, 0x52, 0x0a,
	0x11, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x65, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x04, 0x12, 0x0c, 0x0a,
	0x08, 0x54, 0x69, 0x6d, 0x65, 0x64, 0x6f, 0x75, 0x74, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x65, 0x63, 0x69, 0x64, 0x65, 0x64, 0x10, 0x06, 0x22, 0x4c, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c, 0x0a, 0x06, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x36, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x34, 0x0a, 0x04, 0x52, 0x65,
	0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x7e, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x12,
	0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x22, 0x89, 0x01, 0x0a, 0x07, 0x4c, 0x6f, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x04,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x78, 0x6e,
	0x2e, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x28,
	0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x74, 0x78, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x32, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x75, 0x73, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x75,
	0x73, 0x74, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x02, 0x22, 0x93, 0x01, 0x0a,
	0x09, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2a,
	0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x74, 0x78, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x36, 0x0a, 0x05, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x4d, 0x75, 0x73, 0x74, 0x42, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x4d, 0x75, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x42, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x10, 0x02, 0x22, 0x55, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a,
	0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22, 0x7b, 0x0a, 0x09, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x6c,
	0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22, 0xed, 0x02, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65,
	0x61, 0x64, 0x12, 0x2f, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x78, 0x6e,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x25, 0x0a, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x48, 0x00,
	0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x29, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x48,
	0x00, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x0a, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00,
	0x52, 0x09, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x08,
	0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x2f, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x78,
	0x6e, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x09, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x2a, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0xe4, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2a, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x74, 0x78, 0x6e, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0x72, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x65, 0x79, 0x4e, 0x6f,
	0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x65, 0x79, 0x41,
	0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x10, 0x02, 0x12, 0x13,
	0x0a, 0x0f, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x75, 0x70, 0x74, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x10, 0x05, 0x22, 0x66, 0x0a, 0x08, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07,
	0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x99,
	0x01, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x03, 0x74,
	0x78, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x54,
	0x78, 0x6e, 0x52, 0x03, 0x74, 0x78, 0x6e, 0x12, 0x1f, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x4c, 0x6f, 0x63,
	0x6b, 0x52, 0x05, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x12,
	0x29, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x78, 0x6e, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x63, 0x72, 0x75, 0x73, 0x75, 0x2f,
	0x73, 0x63, 0x6f, 0x75, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x78, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_data_server_txn_txn_proto_rawDescOnce sync.Once
	file_internal_data_server_txn_txn_proto_rawDescData = file_internal_data_server_txn_txn_proto_rawDesc
)

func file_internal_data_server_txn_txn_proto_rawDescGZIP() []byte {
	file_internal_data_server_txn_txn_proto_rawDescOnce.Do(func() {
		file_internal_data_server_txn_txn_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_data_server_txn_txn_proto_rawDescData)
	})
	return file_internal_data_server_txn_txn_proto_rawDescData
}

var file_internal_data_server_txn_txn_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_internal_data_server_txn_txn_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_internal_data_server_txn_txn_proto_goTypes = []any{
	(Status_State)(0),      // 0: txn.Status.State
	(LockKey_Check)(0),     // 1: txn.LockKey.Check
	(LockRange_Check)(0),   // 2: txn.LockRange.Check
	(ActionStatus_Code)(0), // 3: txn.ActionStatus.Code
	(*Snapshot)(nil),       // 4: txn.Snapshot
	(*Autocommit)(nil),     // 5: txn.Autocommit
	(*Prepare)(nil),        // 6: txn.Prepare
	(*Commit)(nil),         // 7: txn.Commit
	(*Abort)(nil),          // 8: txn.Abort
	(*StoreDecision)(nil),  // 9: txn.StoreDecision
	(*MarkTimedout)(nil),   // 10: txn.MarkTimedout
	(*Batch)(nil),          // 11: txn.Batch
	(*Id)(nil),             // 12: txn.Id
	(*Txn)(nil),            // 13: txn.Txn
	(*Status)(nil),         // 14: txn.Status
	(*Insert)(nil),         // 15: txn.Insert
	(*Update)(nil),         // 16: txn.Update
	(*Upsert)(nil),         // 17: txn.Upsert
	(*Delete)(nil),         // 18: txn.Delete
	(*Read)(nil),           // 19: txn.Read
	(*ReadRange)(nil),      // 20: txn.ReadRange
	(*LockKey)(nil),        // 21: txn.LockKey
	(*LockRange)(nil),      // 22: txn.LockRange
	(*KeyLock)(nil),        // 23: txn.KeyLock
	(*RangeLock)(nil),      // 24: txn.RangeLock
	(*Action)(nil),         // 25: txn.Action
	(*Lock)(nil),           // 26: txn.Lock
	(*Value)(nil),          // 27: txn.Value
	(*ActionStatus)(nil),   // 28: txn.ActionStatus
	(*Decision)(nil),       // 29: txn.Decision
	(*Prepared)(nil),       // 30: txn.Prepared
	nil,                    // 31: txn.Status.ActionStatusEntry
}
var file_internal_data_server_txn_txn_proto_depIdxs = []int32{
	14, // 0: txn.Snapshot.status:type_name -> txn.Status
	30, // 1: txn.Snapshot.prepared:type_name -> txn.Prepared
	13, // 2: txn.Autocommit.txn:type_name -> txn.Txn
	13, // 3: txn.Prepare.txn:type_name -> txn.Txn
	12, // 4: txn.Commit.id:type_name -> txn.Id
	12, // 5: txn.Abort.id:type_name -> txn.Id
	29, // 6: txn.StoreDecision.decision:type_name -> txn.Decision
	12, // 7: txn.MarkTimedout.id:type_name -> txn.Id
	5,  // 8: txn.Batch.autocommit:type_name -> txn.Autocommit
	6,  // 9: txn.Batch.prepare:type_name -> txn.Prepare
	7,  // 10: txn.Batch.commit:type_name -> txn.Commit
	8,  // 11: txn.Batch.abort:type_name -> txn.Abort
	9,  // 12: txn.Batch.store_decision:type_name -> txn.StoreDecision
	10, // 13: txn.Batch.mark_timedout:type_name -> txn.MarkTimedout
	12, // 14: txn.Txn.id:type_name -> txn.Id
	25, // 15: txn.Txn.actions:type_name -> txn.Action
	12, // 16: txn.Status.id:type_name -> txn.Id
	0,  // 17: txn.Status.state:type_name -> txn.Status.State
	31, // 18: txn.Status.action_status:type_name -> txn.Status.ActionStatusEntry
	23, // 19: txn.LockKey.lock:type_name -> txn.KeyLock
	1,  // 20: txn.LockKey.check:type_name -> txn.LockKey.Check
	24, // 21: txn.LockRange.lock:type_name -> txn.RangeLock
	2,  // 22: txn.LockRange.check:type_name -> txn.LockRange.Check
	19, // 23: txn.Action.read:type_name -> txn.Read
	20, // 24: txn.Action.read_range:type_name -> txn.ReadRange
	15, // 25: txn.Action.insert:type_name -> txn.Insert
	16, // 26: txn.Action.update:type_name -> txn.Update
	17, // 27: txn.Action.upsert:type_name -> txn.Upsert
	18, // 28: txn.Action.delete:type_name -> txn.Delete
	21, // 29: txn.Action.lock_key:type_name -> txn.LockKey
	22, // 30: txn.Action.lock_range:type_name -> txn.LockRange
	23, // 31: txn.Lock.key_lock:type_name -> txn.KeyLock
	24, // 32: txn.Lock.range_lock:type_name -> txn.RangeLock
	3,  // 33: txn.ActionStatus.code:type_name -> txn.ActionStatus.Code
	27, // 34: txn.ActionStatus.results:type_name -> txn.Value
	12, // 35: txn.Decision.id:type_name -> txn.Id
	13, // 36: txn.Prepared.txn:type_name -> txn.Txn
	26, // 37: txn.Prepared.locks:type_name -> txn.Lock
	29, // 38: txn.Prepared.decision:type_name -> txn.Decision
	28, // 39: txn.Status.ActionStatusEntry.value:type_name -> txn.ActionStatus
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_internal_data_server_txn_txn_proto_init() }
func file_internal_data_server_txn_txn_proto_init() {
	if File_internal_data_server_txn_txn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_data_server_txn_txn_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Autocommit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Prepare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Commit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Abort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*StoreDecision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MarkTimedout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Batch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Txn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Insert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Upsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Delete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*Read); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ReadRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*LockKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*LockRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*KeyLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*RangeLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*Lock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*ActionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*Decision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_txn_txn_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*Prepared); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_data_server_txn_txn_proto_msgTypes[21].OneofWrappers = []any{
		(*Action_Read)(nil),
		(*Action_ReadRange)(nil),
		(*Action_Insert)(nil),
		(*Action_Update)(nil),
		(*Action_Upsert)(nil),
		(*Action_Delete)(nil),
		(*Action_LockKey)(nil),
		(*Action_LockRange)(nil),
	}
	file_internal_data_server_txn_txn_proto_msgTypes[22].OneofWrappers = []any{
		(*Lock_KeyLock)(nil),
		(*Lock_RangeLock)(nil),
	}
	file_internal_data_server_txn_txn_proto_msgTypes[23].OneofWrappers = []any{
		(*Value_Bytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_data_server_txn_txn_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_data_server_txn_txn_proto_goTypes,
		DependencyIndexes: file_internal_data_server_txn_txn_proto_depIdxs,
		EnumInfos:         file_internal_data_server_txn_txn_proto_enumTypes,
		MessageInfos:      file_internal_data_server_txn_txn_proto_msgTypes,
	}.Build()
	File_internal_data_server_txn_txn_proto = out.File
	file_internal_data_server_txn_txn_proto_rawDesc = nil
	file_internal_data_server_txn_txn_proto_goTypes = nil
	file_internal_data_server_txn_txn_proto_depIdxs = nil
}
