name: scout

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

networks:
  default:
    driver: bridge

services:
  control1: &control
    image: ${SCOUT_CONTROL_IMAGE}
    hostname: control1
    restart: unless-stopped
    command:
      - "--config-file=/scout/config.yaml"
    volumes:
      - ./scout/config-control.yaml:/scout/config.yaml
    logging: *logging
    depends_on:
      - otelcol

  control2:
    <<: *control
    hostname: control2

  control3:
    <<: *control
    hostname: control3

  data:
    image: ${SCOUT_DATA_IMAGE}
    restart: unless-stopped
    command:
      - "--config-file=/scout/config.yaml"
    volumes:
      - ./scout/config-data.yaml:/scout/config.yaml
    logging: *logging
    depends_on:
      - otelcol
      - control1
      - control2
      - control3
    deploy:
      mode: replicated
      replicas: ${SCOUT_DATA_REPLICAS}

  api:
    image: ${SCOUT_API_IMAGE}
    restart: unless-stopped
    command:
      - "--config-file=/scout/config.yaml"
    volumes:
      - ./scout/config-api.yaml:/scout/config.yaml
    ports:
      - ${SCOUT_API_PORT}
    logging: *logging
    depends_on:
      - otelcol
      - control1
      - control2
      - control3
    deploy:
      mode: replicated
      replicas: ${SCOUT_API_REPLICAS}
      endpoint_mode: vip

  nginx:
    image: ${NGINX_IMAGE}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    logging: *logging
    depends_on:
      - api

  otelcol:
    image: ${OTEL_COLLECTOR_IMAGE}
    hostname: otelcol
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yaml" ]
    user: 0:0
    volumes:
      - ./otelcollector/otelcol-config.yaml:/etc/otelcol-config.yaml
    ports:
      - ${OTEL_COLLECTOR_PORT_GRPC}:${OTEL_COLLECTOR_PORT_GRPC}
      - ${OTEL_COLLECTOR_PORT_HTTP}:${OTEL_COLLECTOR_PORT_HTTP}
    depends_on:
      jaeger:
        condition: service_started
    logging: *logging
    environment:
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
      - OTEL_COLLECTOR_PORT_HTTP

  jaeger:
    image: ${JAEGER_IMAGE}
    hostname: jaeger
    command:
      - "--memory.max-traces=1000"
      - "--query.base-path=/jaeger/ui"
      - "--prometheus.server-url=http://${PROMETHEUS_ADDR}"
      - "--prometheus.query.normalize-calls=true"
      - "--prometheus.query.normalize-duration=true"
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped
    ports:
      - ${JAEGER_SERVICE_PORT}
      - ${OTEL_COLLECTOR_PORT_GRPC}
    environment:
      - METRICS_STORAGE_TYPE=prometheus
    logging: *logging

  grafana:
    image: ${GRAFANA_IMAGE}
    hostname: grafana
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - ${GRAFANA_SERVICE_PORT}:${GRAFANA_SERVICE_PORT}
    logging: *logging

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    hostname: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=30m
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
      - --query.lookback-delta=30s
    volumes:
      - ./prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - ${PROMETHEUS_SERVICE_PORT}
    logging: *logging
