// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.4
// source: internal/data/server/storage/storage.proto

package storage

import (
	data "github.com/bcrusu/graph/internal/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*Command_ExecuteTxnBatch
	Payload isCommand_Payload `protobuf_oneof:"payload"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_storage_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_storage_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_data_server_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (m *Command) GetPayload() isCommand_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Command) GetExecuteTxnBatch() *ExecuteTxnBatch {
	if x, ok := x.GetPayload().(*Command_ExecuteTxnBatch); ok {
		return x.ExecuteTxnBatch
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_ExecuteTxnBatch struct {
	ExecuteTxnBatch *ExecuteTxnBatch `protobuf:"bytes,1,opt,name=execute_txn_batch,json=executeTxnBatch,proto3,oneof"`
}

func (*Command_ExecuteTxnBatch) isCommand_Payload() {}

type ExecuteTxnBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp       uint64        `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Autocommit      []*data.Txn   `protobuf:"bytes,2,rep,name=autocommit,proto3" json:"autocommit,omitempty"`
	TwoPhasePrepare []*data.Txn   `protobuf:"bytes,3,rep,name=two_phase_prepare,json=twoPhasePrepare,proto3" json:"two_phase_prepare,omitempty"`
	TwoPhaseCommit  []*data.TxnId `protobuf:"bytes,4,rep,name=two_phase_commit,json=twoPhaseCommit,proto3" json:"two_phase_commit,omitempty"`
	TwoPhaseAbort   []*data.TxnId `protobuf:"bytes,5,rep,name=two_phase_abort,json=twoPhaseAbort,proto3" json:"two_phase_abort,omitempty"`
}

func (x *ExecuteTxnBatch) Reset() {
	*x = ExecuteTxnBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_storage_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteTxnBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTxnBatch) ProtoMessage() {}

func (x *ExecuteTxnBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_storage_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTxnBatch.ProtoReflect.Descriptor instead.
func (*ExecuteTxnBatch) Descriptor() ([]byte, []int) {
	return file_internal_data_server_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteTxnBatch) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecuteTxnBatch) GetAutocommit() []*data.Txn {
	if x != nil {
		return x.Autocommit
	}
	return nil
}

func (x *ExecuteTxnBatch) GetTwoPhasePrepare() []*data.Txn {
	if x != nil {
		return x.TwoPhasePrepare
	}
	return nil
}

func (x *ExecuteTxnBatch) GetTwoPhaseCommit() []*data.TxnId {
	if x != nil {
		return x.TwoPhaseCommit
	}
	return nil
}

func (x *ExecuteTxnBatch) GetTwoPhaseAbort() []*data.TxnId {
	if x != nil {
		return x.TwoPhaseAbort
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index       uint64            `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	TxnStatus   []*data.TxnStatus `protobuf:"bytes,2,rep,name=txn_status,json=txnStatus,proto3" json:"txn_status,omitempty"`
	TxnPrepared []*TxnPrepared    `protobuf:"bytes,3,rep,name=txn_prepared,json=txnPrepared,proto3" json:"txn_prepared,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_storage_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_storage_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_internal_data_server_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Snapshot) GetTxnStatus() []*data.TxnStatus {
	if x != nil {
		return x.TxnStatus
	}
	return nil
}

func (x *Snapshot) GetTxnPrepared() []*TxnPrepared {
	if x != nil {
		return x.TxnPrepared
	}
	return nil
}

type TxnPrepared struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txn   *data.Txn `protobuf:"bytes,1,opt,name=txn,proto3" json:"txn,omitempty"`
	Locks []*Lock   `protobuf:"bytes,2,rep,name=locks,proto3" json:"locks,omitempty"`
}

func (x *TxnPrepared) Reset() {
	*x = TxnPrepared{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_storage_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnPrepared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnPrepared) ProtoMessage() {}

func (x *TxnPrepared) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_storage_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnPrepared.ProtoReflect.Descriptor instead.
func (*TxnPrepared) Descriptor() ([]byte, []int) {
	return file_internal_data_server_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *TxnPrepared) GetTxn() *data.Txn {
	if x != nil {
		return x.Txn
	}
	return nil
}

func (x *TxnPrepared) GetLocks() []*Lock {
	if x != nil {
		return x.Locks
	}
	return nil
}

type Lock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionIndex uint32 `protobuf:"varint,1,opt,name=action_index,json=actionIndex,proto3" json:"action_index,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Lock_KeyLock
	//	*Lock_RangeLock
	Payload isLock_Payload `protobuf_oneof:"payload"`
}

func (x *Lock) Reset() {
	*x = Lock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_data_server_storage_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lock) ProtoMessage() {}

func (x *Lock) ProtoReflect() protoreflect.Message {
	mi := &file_internal_data_server_storage_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lock.ProtoReflect.Descriptor instead.
func (*Lock) Descriptor() ([]byte, []int) {
	return file_internal_data_server_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *Lock) GetActionIndex() uint32 {
	if x != nil {
		return x.ActionIndex
	}
	return 0
}

func (m *Lock) GetPayload() isLock_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Lock) GetKeyLock() *data.KeyLock {
	if x, ok := x.GetPayload().(*Lock_KeyLock); ok {
		return x.KeyLock
	}
	return nil
}

func (x *Lock) GetRangeLock() *data.RangeLock {
	if x, ok := x.GetPayload().(*Lock_RangeLock); ok {
		return x.RangeLock
	}
	return nil
}

type isLock_Payload interface {
	isLock_Payload()
}

type Lock_KeyLock struct {
	KeyLock *data.KeyLock `protobuf:"bytes,2,opt,name=key_lock,json=keyLock,proto3,oneof"`
}

type Lock_RangeLock struct {
	RangeLock *data.RangeLock `protobuf:"bytes,3,opt,name=range_lock,json=rangeLock,proto3,oneof"`
}

func (*Lock_KeyLock) isLock_Payload() {}

func (*Lock_RangeLock) isLock_Payload() {}

var File_internal_data_server_storage_storage_proto protoreflect.FileDescriptor

var file_internal_data_server_storage_storage_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x1a, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x4b, 0x0a, 0x11, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x5f, 0x74, 0x78, 0x6e,
	0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x54, 0x78, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x48, 0x00, 0x52, 0x0f, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x54, 0x78, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xfd, 0x01, 0x0a, 0x0f, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x54, 0x78, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x29, 0x0a, 0x0a, 0x61,
	0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x6f,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x35, 0x0a, 0x11, 0x74, 0x77, 0x6f, 0x5f, 0x70, 0x68,
	0x61, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x0f, 0x74, 0x77,
	0x6f, 0x50, 0x68, 0x61, 0x73, 0x65, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x35, 0x0a,
	0x10, 0x74, 0x77, 0x6f, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54,
	0x78, 0x6e, 0x49, 0x64, 0x52, 0x0e, 0x74, 0x77, 0x6f, 0x50, 0x68, 0x61, 0x73, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x12, 0x33, 0x0a, 0x0f, 0x74, 0x77, 0x6f, 0x5f, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x5f, 0x61, 0x62, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x78, 0x6e, 0x49, 0x64, 0x52, 0x0d, 0x74, 0x77, 0x6f, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x08, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2e, 0x0a, 0x0a,
	0x74, 0x78, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x09, 0x74, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3c, 0x0a, 0x0c,
	0x74, 0x78, 0x6e, 0x5f, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x54, 0x78, 0x6e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x52, 0x0b, 0x74,
	0x78, 0x6e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x22, 0x54, 0x0a, 0x0b, 0x54, 0x78,
	0x6e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x03, 0x74, 0x78, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x78,
	0x6e, 0x52, 0x03, 0x74, 0x78, 0x6e, 0x12, 0x28, 0x0a, 0x05, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x22, 0x92, 0x01, 0x0a, 0x04, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2a, 0x0a, 0x08,
	0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x30, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52,
	0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x63, 0x72, 0x75, 0x73, 0x75, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_data_server_storage_storage_proto_rawDescOnce sync.Once
	file_internal_data_server_storage_storage_proto_rawDescData = file_internal_data_server_storage_storage_proto_rawDesc
)

func file_internal_data_server_storage_storage_proto_rawDescGZIP() []byte {
	file_internal_data_server_storage_storage_proto_rawDescOnce.Do(func() {
		file_internal_data_server_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_data_server_storage_storage_proto_rawDescData)
	})
	return file_internal_data_server_storage_storage_proto_rawDescData
}

var file_internal_data_server_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_data_server_storage_storage_proto_goTypes = []any{
	(*Command)(nil),         // 0: data.storage.Command
	(*ExecuteTxnBatch)(nil), // 1: data.storage.ExecuteTxnBatch
	(*Snapshot)(nil),        // 2: data.storage.Snapshot
	(*TxnPrepared)(nil),     // 3: data.storage.TxnPrepared
	(*Lock)(nil),            // 4: data.storage.Lock
	(*data.Txn)(nil),        // 5: data.Txn
	(*data.TxnId)(nil),      // 6: data.TxnId
	(*data.TxnStatus)(nil),  // 7: data.TxnStatus
	(*data.KeyLock)(nil),    // 8: data.KeyLock
	(*data.RangeLock)(nil),  // 9: data.RangeLock
}
var file_internal_data_server_storage_storage_proto_depIdxs = []int32{
	1,  // 0: data.storage.Command.execute_txn_batch:type_name -> data.storage.ExecuteTxnBatch
	5,  // 1: data.storage.ExecuteTxnBatch.autocommit:type_name -> data.Txn
	5,  // 2: data.storage.ExecuteTxnBatch.two_phase_prepare:type_name -> data.Txn
	6,  // 3: data.storage.ExecuteTxnBatch.two_phase_commit:type_name -> data.TxnId
	6,  // 4: data.storage.ExecuteTxnBatch.two_phase_abort:type_name -> data.TxnId
	7,  // 5: data.storage.Snapshot.txn_status:type_name -> data.TxnStatus
	3,  // 6: data.storage.Snapshot.txn_prepared:type_name -> data.storage.TxnPrepared
	5,  // 7: data.storage.TxnPrepared.txn:type_name -> data.Txn
	4,  // 8: data.storage.TxnPrepared.locks:type_name -> data.storage.Lock
	8,  // 9: data.storage.Lock.key_lock:type_name -> data.KeyLock
	9,  // 10: data.storage.Lock.range_lock:type_name -> data.RangeLock
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_data_server_storage_storage_proto_init() }
func file_internal_data_server_storage_storage_proto_init() {
	if File_internal_data_server_storage_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_data_server_storage_storage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_storage_storage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ExecuteTxnBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_storage_storage_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_storage_storage_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TxnPrepared); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_data_server_storage_storage_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Lock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_data_server_storage_storage_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_ExecuteTxnBatch)(nil),
	}
	file_internal_data_server_storage_storage_proto_msgTypes[4].OneofWrappers = []any{
		(*Lock_KeyLock)(nil),
		(*Lock_RangeLock)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_data_server_storage_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_data_server_storage_storage_proto_goTypes,
		DependencyIndexes: file_internal_data_server_storage_storage_proto_depIdxs,
		MessageInfos:      file_internal_data_server_storage_storage_proto_msgTypes,
	}.Build()
	File_internal_data_server_storage_storage_proto = out.File
	file_internal_data_server_storage_storage_proto_rawDesc = nil
	file_internal_data_server_storage_storage_proto_goTypes = nil
	file_internal_data_server_storage_storage_proto_depIdxs = nil
}
